export const IPC_CHANNELS = {
  GITHUB_AUTH_STATUS: 'github:auth-status',
  GITHUB_AUTH_START: 'github:auth-start',
  GITHUB_AUTH_COMPLETE: 'github:auth-complete',
  GITHUB_AUTH_CANCEL: 'github:auth-cancel',
  GITHUB_AUTH_REFRESH_INSTALLATIONS: 'github:auth-refresh-installations',
  GITHUB_AUTH_LOGOUT: 'github:auth-logout',
  GITHUB_AUTH_RETRY_SESSION: 'github:auth-retry-session',
  GITHUB_AUTH_STATUS_CHANGED: 'github:auth-status-changed',
  GITHUB_AUTH_OPEN_DEVICE_VERIFICATION:
    'github:auth-open-device-verification',
  GITHUB_AUTH_OPEN_INSTALLATION: 'github:auth-open-installation',
  GITHUB_AUTH_OPEN_AUTHORIZATION_SETTINGS:
    'github:auth-open-authorization-settings',
  GITHUB_LIST_REPOS: 'github:list-repos',
  GITHUB_LIST_REMOTE_REPOS: 'github:list-remote-repos',
  GITHUB_LIST_BRANCHES: 'github:list-branches',
  GIT_CREATE_BRANCH: 'git:create-branch',
  REPOSITORY_IMPORT_LOCAL: 'repository:import-local',
  REPOSITORY_IMPORT_REMOTE: 'repository:import-remote',
  WORKTREE_CREATE: 'worktree:create',
  WORKTREE_LIST: 'worktree:list',
  WORKTREE_LIST_ALL: 'worktree:list-all',
  EDITOR_LIST_AVAILABLE: 'editor:list-available',
  EDITOR_OPEN: 'editor:open',
  CODING_AGENT_SELECT_EXECUTABLE: 'coding-agent:select-executable',
  CODING_AGENT_STATUS: 'coding-agent:status',
  CODING_AGENT_MODELS: 'coding-agent:models',
  CODING_AGENT_WORKTREES: 'coding-agent:worktrees',
  CODING_AGENT_SESSION_LIST: 'coding-agent:session-list',
  CODING_AGENT_SESSION_CREATE: 'coding-agent:session-create',
  CODING_AGENT_SESSION_MODEL_UPDATE: 'coding-agent:session-model-update',
  CODING_AGENT_SESSION_GET: 'coding-agent:session-get',
  CODING_AGENT_SESSION_USAGE: 'coding-agent:session-usage',
  CODING_AGENT_SESSION_SEND: 'coding-agent:session-send',
  CODING_AGENT_SESSION_COMPACT: 'coding-agent:session-compact',
  CODING_AGENT_SESSION_ABORT: 'coding-agent:session-abort',
  CODING_AGENT_PERMISSION_RESPOND: 'coding-agent:permission-respond',
  CODING_AGENT_EVENT: 'coding-agent:event',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
