// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";import {afterEach,describe,expect,it,vi} from "vitest";import {useMarketplace} from "./useMarketplace";
afterEach(cleanup);const capability={id:"web",name:"Web",description:"Search",version:"1",category:"search",source:"bundled",compatibility:{codex:"supported",opencode:"supported"},state:"ready"};const skill={id:"review",name:"review",description:"Review",version:"1",source:"local",compatibility:{codex:"supported",opencode:"supported"},installationState:"installed",automaticInvocation:true} as const;
function Probe(){const value=useMarketplace();return <div>{value.items.map(x=>x.kind).join(",")||"empty"}</div>}
describe("useMarketplace",()=>{it("aggregates capabilities and skills",async()=>{const unsubA=vi.fn(),unsubB=vi.fn();Object.defineProperty(window,"api",{configurable:true,value:{capabilities:{list:vi.fn(async()=>[capability]),onChanged:vi.fn(()=>unsubA)},skills:{list:vi.fn(async()=>[skill]),onChanged:vi.fn(()=>unsubB)}}});const result=render(<Probe/>);await waitFor(()=>expect(screen.getByText("capability,skill")).toBeTruthy());result.unmount();expect(unsubA).toHaveBeenCalled();expect(unsubB).toHaveBeenCalled();});
 it("coalesces initial loading into a combined list",async()=>{Object.defineProperty(window,"api",{configurable:true,value:{capabilities:{list:vi.fn(async()=>[]),onChanged:vi.fn(()=>()=>undefined)},skills:{list:vi.fn(async()=>[]),onChanged:vi.fn(()=>()=>undefined)}}});render(<Probe/>);await waitFor(()=>expect(screen.getByText("empty")).toBeTruthy());});});

function ActionProbe(){const value=useMarketplace();return <div><button onClick={()=>void value.install()}>install</button><button onClick={()=>void value.remove("review")}>remove</button><button onClick={()=>void value.select({kind:"skill",skill})}>detail</button><span>{value.loading?"loading":"ready"}</span><span>{value.error}</span></div>}
describe("marketplace action errors",()=>{it.each([["install","Could not install the skill."],["remove","Could not remove the skill."],["detail","Could not load marketplace item details."]] as const)("captures %s rejection",async(action,message)=>{Object.defineProperty(window,"api",{configurable:true,value:{capabilities:{list:vi.fn(async()=>[]),onChanged:vi.fn(()=>()=>undefined)},skills:{list:vi.fn(async()=>[]),onChanged:vi.fn(()=>()=>undefined),install:vi.fn(async()=>{throw new Error("secret")}),remove:vi.fn(async()=>{throw new Error("secret")}),get:vi.fn(async()=>{throw new Error("secret")})}}});render(<ActionProbe/>);await waitFor(()=>expect(screen.getByText("ready")).toBeTruthy());fireEvent.click(screen.getByRole("button",{name:action}));await waitFor(()=>expect(screen.getByText(message)).toBeTruthy());});});
