import {
  assignmentProjectionSchema,
  type AssignmentProjectionDto,
} from "../../../../shared/assignments/schemas";
export const initialProjection = (): AssignmentProjectionDto =>
  assignmentProjectionSchema.parse({
    worktreeId: "wt",
    revision: "4",
    projectionSequence: "8",
    phase: "stable",
    currentAgentKind: "codex",
    resources: [
      {
        kind: "skill",
        id: "review",
        name: "Security Review",
        version: "1.0",
        description: "Review changes",
        desired: true,
        verified: true,
        operation: null,
        status: "enabled",
        assignable: true,
        unavailableReason: null,
        automaticUsageReporting: "unknown",
        skillIsolation: "not_enforced",
      },
      {
        kind: "capability",
        id: "fetch",
        name: "URL Fetch",
        version: "2.0",
        description: "Fetch public pages",
        desired: false,
        verified: false,
        operation: null,
        status: "installed",
        assignable: true,
        unavailableReason: null,
        automaticUsageReporting: "not_applicable",
        skillIsolation: "not_applicable",
      },
    ],
    blockers: [],
    progress: null,
    admission: {
      canCreateSession: true,
      canResumeSession: true,
      canSend: true,
      reason: null,
      message: null,
    },
    allowedActions: [],
    failure: null,
    updatedAt: "2026-10-03T10:00:00.000Z",
  });
