import { existsSync } from "node:fs";
import { mkdtemp, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import type { CapabilityStaticDescriptor } from "@agentic-worktrees/capability-sdk";
import { CapabilityPackageInspector, MAX_CAPABILITY_METADATA_BYTES } from "./package-inspector";

const descriptor: CapabilityStaticDescriptor = { manifest: { id: "agentic-worktrees.example", name: "Example", version: "1.0.0", sdkVersion: "^0.1.0", description: "Example", category: "test", author: { name: "Test" }, license: "MIT", compatibility: { codex: "supported", opencode: "supported" }, permissions: { network: [], secrets: [] }, settings: {} }, tools: [{ name: "example", description: "Example", inputSchema: { type: "object" } }] };
async function fixture(packageOverrides: Record<string, unknown> = {}, descriptorValue: unknown = descriptor) { const root = await mkdtemp(join(tmpdir(), "cap-inspect-")); const pkg = { name: "@example/cap", version: "1.0.0", agenticWorktrees: { kind: "capability", manifest: "capability.json", entry: "dist/index.js" }, ...packageOverrides }; await writeFile(join(root, "package.json"), JSON.stringify(pkg)); await writeFile(join(root, "capability.json"), JSON.stringify(descriptorValue)); await writeFile(join(root, "entry-marker.js"), ""); return { root, staged: { operationId: "op", packageRoot: root, packageJson: pkg, contentDigest: "digest", requestedSpec: "@example/cap@1.0.0", packageName: "@example/cap", resolvedVersion: "1.0.0", integrity: "integrity" } }; }
describe("CapabilityPackageInspector", () => {
  it("reads metadata without executing the entry", async () => { const { root, staged } = await fixture({ agenticWorktrees: { kind: "capability", manifest: "capability.json", entry: "entry.js" } }); const marker = join(root, "marker"); await writeFile(join(root, "entry.js"), `require('node:fs').writeFileSync(${JSON.stringify(marker)}, 'ran')`); const result = await new CapabilityPackageInspector().inspect(staged, { trust: "community", reviewStatus: "unreviewed" }); expect(result.descriptor.manifest.id).toBe("agentic-worktrees.example"); expect(existsSync(marker)).toBe(false); });
  it.each([{ agenticWorktrees: undefined }, { agenticWorktrees: { kind: "skill", manifest: "capability.json", entry: "x" } }, { agenticWorktrees: { kind: "capability", manifest: "../capability.json", entry: "x" } }, { agenticWorktrees: { kind: "capability", manifest: "capability.json", entry: "/x" } }, { scripts: { postinstall: "evil" } }])("rejects unsafe package metadata %#", async override => { const { staged } = await fixture(override as Record<string, unknown>); await expect(new CapabilityPackageInspector().inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow(); });
  it("rejects descriptor/version/sdk/id and Official mismatches", async () => { const { staged } = await fixture(); await expect(new CapabilityPackageInspector({ sdkVersion: "2.0.0" }).inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("SDK"); await expect(new CapabilityPackageInspector({ reservedCapabilityIds: [descriptor.manifest.id] }).inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("collides"); await expect(new CapabilityPackageInspector().inspect(staged, { trust: "official", reviewStatus: "official-reviewed" })).rejects.toThrow("Official"); const bad = await fixture({}, { ...descriptor, manifest: { ...descriptor.manifest, version: "2.0.0" } }); await expect(new CapabilityPackageInspector().inspect(bad.staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("version"); });
  it("reads package identity from disk rather than staged packageJson", async () => { const { staged } = await fixture({ name: "@disk/truth" }); staged.packageJson.name = staged.packageName; await expect(new CapabilityPackageInspector().inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("metadata"); });
  it.each(["package.json", "capability.json"])("rejects oversized %s metadata", async file => { const { root, staged } = await fixture(); await writeFile(join(root, file), " ".repeat(MAX_CAPABILITY_METADATA_BYTES + 1)); await expect(new CapabilityPackageInspector().inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow(); });
  it("rejects a manifest symlink escape", async () => { const { root, staged } = await fixture(); const outside = join(root, "..", `manifest-${Date.now()}.json`); await writeFile(outside, JSON.stringify(descriptor)); await writeFile(join(root, "package.json"), JSON.stringify({ name: staged.packageName, version: staged.resolvedVersion, agenticWorktrees: { kind: "capability", manifest: "linked.json", entry: "dist/index.js" } })); await symlink(outside, join(root, "linked.json")); await expect(new CapabilityPackageInspector().inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("descriptor"); });
  it.each(["preinstall", "install", "postinstall", "prepare"])("rejects the %s lifecycle script", async script => { const { staged } = await fixture({ scripts: { [script]: "echo unsafe" } }); await expect(new CapabilityPackageInspector().inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("lifecycle"); });
});
