import { existsSync } from "node:fs";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import type { CapabilityStaticDescriptor } from "@agentic-worktrees/capability-sdk";
import { CapabilityPackageInspector } from "./package-inspector";

const descriptor: CapabilityStaticDescriptor = { manifest: { id: "agentic-worktrees.example", name: "Example", version: "1.0.0", sdkVersion: "^0.1.0", description: "Example", category: "test", author: { name: "Test" }, license: "MIT", compatibility: { codex: "supported", opencode: "supported" }, permissions: { network: [], secrets: [] }, settings: {} }, tools: [{ name: "example", description: "Example", inputSchema: { type: "object" } }] };
async function fixture(packageOverrides: Record<string, unknown> = {}, descriptorValue: unknown = descriptor) { const root = await mkdtemp(join(tmpdir(), "cap-inspect-")); const pkg = { name: "@example/cap", version: "1.0.0", agenticWorktrees: { kind: "capability", manifest: "capability.json", entry: "dist/index.js" }, ...packageOverrides }; await writeFile(join(root, "package.json"), JSON.stringify(pkg)); await writeFile(join(root, "capability.json"), JSON.stringify(descriptorValue)); await writeFile(join(root, "entry-marker.js"), ""); return { root, staged: { operationId: "op", packageRoot: root, packageJson: pkg, contentDigest: "digest", requestedSpec: "@example/cap@1.0.0", packageName: "@example/cap", resolvedVersion: "1.0.0", integrity: "integrity" } }; }
describe("CapabilityPackageInspector", () => {
  it("reads metadata without executing the entry", async () => { const { root, staged } = await fixture({ agenticWorktrees: { kind: "capability", manifest: "capability.json", entry: "entry.js" } }); const marker = join(root, "marker"); await writeFile(join(root, "entry.js"), `require('node:fs').writeFileSync(${JSON.stringify(marker)}, 'ran')`); const result = await new CapabilityPackageInspector().inspect(staged, { trust: "community", reviewStatus: "unreviewed" }); expect(result.descriptor.manifest.id).toBe("agentic-worktrees.example"); expect(existsSync(marker)).toBe(false); });
  it.each([{ agenticWorktrees: undefined }, { agenticWorktrees: { kind: "skill", manifest: "capability.json", entry: "x" } }, { agenticWorktrees: { kind: "capability", manifest: "../capability.json", entry: "x" } }, { agenticWorktrees: { kind: "capability", manifest: "capability.json", entry: "/x" } }, { scripts: { postinstall: "evil" } }])("rejects unsafe package metadata %#", async override => { const { staged } = await fixture(override as Record<string, unknown>); await expect(new CapabilityPackageInspector().inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow(); });
  it("rejects descriptor/version/sdk/id and Official mismatches", async () => { const { staged } = await fixture(); await expect(new CapabilityPackageInspector({ sdkVersion: "2.0.0" }).inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("SDK"); await expect(new CapabilityPackageInspector({ reservedCapabilityIds: [descriptor.manifest.id] }).inspect(staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("collides"); await expect(new CapabilityPackageInspector().inspect(staged, { trust: "official", reviewStatus: "official-reviewed" })).rejects.toThrow("Official"); const bad = await fixture({}, { ...descriptor, manifest: { ...descriptor.manifest, version: "2.0.0" } }); await expect(new CapabilityPackageInspector().inspect(bad.staged, { trust: "community", reviewStatus: "unreviewed" })).rejects.toThrow("version"); });
});
