import { describe, expect, it, vi } from "vitest";
import { createMarketplaceHandlers } from "./marketplace-handlers";

const detail = { id:"agentic-worktrees.web-search", name:"Web Search", version:"1.0.0", sdkVersion:"^0.1.0", description:"Search", category:"search", author:{name:"Agentic Worktrees"}, license:"MIT", compatibility:{codex:"supported",opencode:"supported"}, permissions:{network:[],secrets:[]}, settings:[], state:"ready", secretConfigured:false, installationState:"installed", source:"npm", packageName:"@agentic-worktrees/web-search", trust:"official", reviewStatus:"official-reviewed", activeRunCount:0, providedTools:["web_search"], permissionDigest:"digest" };
const progress = { operationId:"op-1", capabilityId:"agentic-worktrees.web-search", packageName:"@agentic-worktrees/web-search", action:"install", stage:"installing", status:"completed", updatedAt:"2026-09-02T00:00:00.000Z" };

function fixture(overrides: Record<string, unknown> = {}) {
 const distribution = { listMarketplaceCapabilities:vi.fn(async()=>[detail]), inspect:vi.fn(async()=>({inspectionId:"i",packageName:"@agentic-worktrees/web-search",requestedSpec:"@agentic-worktrees/web-search",resolvedVersion:"1",integrity:"sha",contentDigest:"digest",trust:"official",reviewStatus:"official-reviewed",releaseNotes:"",capability:detail,permissionDigest:"p",expiresAt:"2026-09-02T00:00:00.000Z"})), install:vi.fn(async()=>detail), checkForUpdates:vi.fn(async()=>[]), update:vi.fn(async()=>detail), inspectRemoval:vi.fn(async()=>({inspectionId:"i",packageName:"@agentic-worktrees/web-search",capabilityId:"agentic-worktrees.web-search",activeVersion:"1",activeIntegrity:"sha",activeContentDigest:"digest",activeRunCount:0,expiresAt:"2026-09-02T00:00:00.000Z"})), remove:vi.fn(async()=>undefined), cancel:vi.fn(async()=>undefined), retryPendingMigrations:vi.fn(async()=>undefined), ...overrides };
 const skills = { listSkills:vi.fn(()=>[]) };
 return { distribution, skills, handlers:createMarketplaceHandlers(distribution as never, skills as never) };
}

describe("marketplace IPC handlers",()=>{
 it("strips unknown inspect input and rejects malformed input before delegation",async()=>{const f=fixture();await f.handlers.inspect({sourceSpec:"@scope/pkg",injectedPath:"/secret"});expect(f.distribution.inspect).toHaveBeenCalledWith({sourceSpec:"@scope/pkg",intent:"install"});await expect(f.handlers.inspect({sourceSpec:"file:../secret"})).rejects.toThrow(/^package_source_invalid$/);expect(f.distribution.inspect).toHaveBeenCalledOnce();});
 it("maps all lifecycle operations including reviewed removal",async()=>{const f=fixture();await f.handlers.install({inspectionId:"i",acceptedPackageName:"@scope/pkg",acceptedVersion:"1",acceptedIntegrity:"sha",acceptedPermissionDigest:"p",path:"/secret"});await f.handlers.checkUpdates({packageName:"@scope/pkg",path:"/secret"});await f.handlers.update({inspectionId:"i",acceptedPackageName:"@scope/pkg",acceptedVersion:"1",acceptedIntegrity:"sha",acceptedPermissionDigest:"p",packageName:"@scope/pkg",acceptedDowngrade:false,acceptedActiveRunCount:0,path:"/secret"});await f.handlers.inspectRemoval({packageName:"@scope/pkg"});await f.handlers.remove({inspectionId:"i",packageName:"@scope/pkg",acceptedActiveVersion:"1",acceptedActiveRunCount:0});await f.handlers.cancel({operationId:"op"});await f.handlers.retryPendingMigrations({});expect(f.distribution.install).toHaveBeenCalledWith(expect.not.objectContaining({path:expect.anything()}));expect(f.distribution.inspectRemoval).toHaveBeenCalledOnce();expect(f.distribution.remove).toHaveBeenCalledOnce();expect(f.distribution.cancel).toHaveBeenCalledWith("op");expect(f.distribution.retryPendingMigrations).toHaveBeenCalledOnce();});
 it("combines path-free capability and skill catalog items",async()=>{const f=fixture();const value=await f.handlers.list({});expect(value).toMatchObject([{kind:"capability",capability:{id:detail.id,packageName:detail.packageName}}]);expect(JSON.stringify(value)).not.toMatch(/path|token|secret"/i);});
 it("maps malformed backend DTOs and events to stable errors",async()=>{const f=fixture({install:vi.fn(async()=>({...detail,executablePath:"/secret",id:"INVALID ID"}))});await expect(f.handlers.install({inspectionId:"i",acceptedPackageName:"@scope/pkg",acceptedVersion:"1",acceptedIntegrity:"sha",acceptedPermissionDigest:"p"})).rejects.toThrow(/^package_install_failed$/);expect(()=>f.handlers.event({...progress,packageRoot:"/secret"})).toThrow("package_sync_failed");expect(fixture().handlers.event(progress)).toEqual(progress);});
 it("contains skill-list and path-bearing service failures",async()=>{const listFixture=fixture();listFixture.skills.listSkills.mockImplementation(()=>{throw new Error("Zod path /Users/private")});await expect(listFixture.handlers.list({})).rejects.toThrow(/^package_sync_failed$/);const f=fixture({remove:vi.fn(async()=>{throw new Error("failed at /Users/private/package")})});await expect(f.handlers.remove({inspectionId:"i",packageName:"@scope/pkg",acceptedActiveVersion:"1",acceptedActiveRunCount:0})).rejects.toThrow("package_remove_failed");});
});
