import { describe, expect, it, vi } from "vitest";
import { MarketplaceEventSubscription } from "./marketplace-event-subscription";

describe("MarketplaceEventSubscription",()=>{
 it("subscribes once, releases replacements, and makes stale callbacks harmless",()=>{let firstCallback:((event:never)=>void)|undefined;const firstOff=vi.fn(),secondOff=vi.fn(),first={subscribe:vi.fn((callback:(event:never)=>void)=>{firstCallback=callback;return firstOff})},second={subscribe:vi.fn(()=>secondOff)},owner=new MarketplaceEventSubscription(),listener=vi.fn(()=>{throw new Error("listener failed")});owner.configure(first as never,listener);owner.configure(first as never,listener);expect(first.subscribe).toHaveBeenCalledOnce();expect(()=>firstCallback?.({} as never)).not.toThrow();owner.configure(second as never,listener);expect(firstOff).toHaveBeenCalledOnce();expect(second.subscribe).toHaveBeenCalledOnce();expect(()=>firstCallback?.({} as never)).not.toThrow();expect(listener).toHaveBeenCalledOnce();owner.configure(null,listener);expect(secondOff).toHaveBeenCalledOnce();});
 it("continues replacement after unsubscribe throws and reports only a safe code",()=>{const report=vi.fn(),nextOff=vi.fn(),first={subscribe:vi.fn(()=>()=>{throw new Error("/private/path")})},next={subscribe:vi.fn(()=>nextOff)},owner=new MarketplaceEventSubscription(report);owner.configure(first as never,vi.fn());expect(()=>owner.configure(next as never,vi.fn())).not.toThrow();expect(next.subscribe).toHaveBeenCalledOnce();expect(report).toHaveBeenCalledWith("marketplace_event_unsubscribe_failed");expect(JSON.stringify(report.mock.calls)).not.toContain("/private/path");owner.configure(null,vi.fn());expect(nextOff).toHaveBeenCalledOnce();});
 it("leaves no stale service after subscribe throws and permits a later replacement",()=>{const report=vi.fn(),broken={subscribe:vi.fn(()=>{throw new Error("/private/path")})},goodOff=vi.fn(),good={subscribe:vi.fn(()=>goodOff)},owner=new MarketplaceEventSubscription(report);expect(()=>owner.configure(broken as never,vi.fn())).not.toThrow();expect(report).toHaveBeenCalledWith("marketplace_event_subscribe_failed");owner.configure(broken as never,vi.fn());expect(broken.subscribe).toHaveBeenCalledTimes(2);owner.configure(good as never,vi.fn());expect(good.subscribe).toHaveBeenCalledOnce();owner.configure(null,vi.fn());expect(goodOff).toHaveBeenCalledOnce();});
 it("replaces and tears down safely when unsubscribe reporting throws",()=>{const report=vi.fn(()=>{throw new Error("reporter failed")}),first={subscribe:vi.fn(()=>()=>{throw new Error("unsubscribe failed")})},nextOff=vi.fn(),next={subscribe:vi.fn(()=>nextOff)},owner=new MarketplaceEventSubscription(report);owner.configure(first as never,vi.fn());expect(()=>owner.configure(next as never,vi.fn())).not.toThrow();expect(next.subscribe).toHaveBeenCalledOnce();expect(()=>owner.configure(null,vi.fn())).not.toThrow();expect(nextOff).toHaveBeenCalledOnce();});
 it("retries a failed subscribe when subscribe reporting throws",()=>{const report=vi.fn(()=>{throw new Error("reporter failed")}),broken={subscribe:vi.fn(()=>{throw new Error("subscribe failed")})},goodOff=vi.fn(),good={subscribe:vi.fn(()=>goodOff)},owner=new MarketplaceEventSubscription(report);expect(()=>owner.configure(broken as never,vi.fn())).not.toThrow();expect(()=>owner.configure(broken as never,vi.fn())).not.toThrow();expect(broken.subscribe).toHaveBeenCalledTimes(2);expect(()=>owner.configure(good as never,vi.fn())).not.toThrow();expect(good.subscribe).toHaveBeenCalledOnce();owner.configure(null,vi.fn());expect(goodOff).toHaveBeenCalledOnce();});
});
