import { beforeEach, describe, expect, it, vi } from "vitest";
import { ipcRenderer } from "electron";
import { IPC_CHANNELS } from "./shared/ipc/channels";
const mocks=vi.hoisted(()=>({api:null as unknown,listeners:new Map<string,(e:unknown,p:unknown)=>void>(),remove:vi.fn()}));
vi.mock("electron",()=>({contextBridge:{exposeInMainWorld:vi.fn((_n:string,v:unknown)=>{mocks.api=v})},ipcRenderer:{invoke:vi.fn(),on:vi.fn((c:string,l:(e:unknown,p:unknown)=>void)=>mocks.listeners.set(c,l)),removeListener:mocks.remove}}));
describe("marketplace preload",()=>{beforeEach(async()=>{vi.resetModules();mocks.listeners.clear();mocks.remove.mockClear();vi.mocked(ipcRenderer.invoke).mockReset();await import("./preload")});
 it("maps every narrow method to its dedicated channel",async()=>{const api=(mocks.api as import("./shared/ipc/api").Api).marketplace;const calls:[()=>Promise<unknown>,string][]=[
  [()=>api.list(),IPC_CHANNELS.MARKETPLACE_LIST],[()=>api.inspect({sourceSpec:"@scope/pkg"}),IPC_CHANNELS.MARKETPLACE_INSPECT],[()=>api.install({inspectionId:"i",acceptedPackageName:"@scope/pkg",acceptedVersion:"1",acceptedIntegrity:"sha",acceptedPermissionDigest:"p"}),IPC_CHANNELS.MARKETPLACE_INSTALL],[()=>api.checkUpdates(),IPC_CHANNELS.MARKETPLACE_CHECK_UPDATES],[()=>api.update({inspectionId:"i",acceptedPackageName:"@scope/pkg",acceptedVersion:"1",acceptedIntegrity:"sha",acceptedPermissionDigest:"p",packageName:"@scope/pkg",acceptedDowngrade:false,acceptedActiveRunCount:0}),IPC_CHANNELS.MARKETPLACE_UPDATE],[()=>api.inspectRemoval({packageName:"@scope/pkg"}),IPC_CHANNELS.MARKETPLACE_INSPECT_REMOVAL],[()=>api.remove({inspectionId:"i",packageName:"@scope/pkg",acceptedActiveVersion:"1",acceptedActiveRunCount:0}),IPC_CHANNELS.MARKETPLACE_REMOVE],[()=>api.cancel({operationId:"op"}),IPC_CHANNELS.MARKETPLACE_CANCEL],[()=>api.retryPendingMigrations(),IPC_CHANNELS.MARKETPLACE_RETRY_PENDING_MIGRATIONS]];
  for(const [call,channel] of calls){vi.mocked(ipcRenderer.invoke).mockResolvedValueOnce(channel===IPC_CHANNELS.MARKETPLACE_LIST||channel===IPC_CHANNELS.MARKETPLACE_CHECK_UPDATES?[]:undefined);try{await call()}catch{}expect(ipcRenderer.invoke).toHaveBeenLastCalledWith(channel,expect.anything())}
 });
 it("validates progress and removes the exact event listener",()=>{const api=(mocks.api as import("./shared/ipc/api").Api).marketplace,listener=vi.fn(),off=api.onPackageChanged(listener),registered=mocks.listeners.get(IPC_CHANNELS.MARKETPLACE_PACKAGE_CHANGED)!;registered({}, {operationId:"op",action:"install",stage:"installing",status:"completed",updatedAt:"2026-09-02T00:00:00.000Z"});expect(listener).toHaveBeenCalledOnce();expect(()=>registered({}, {operationId:"op",action:"install",stage:"installing",status:"completed",updatedAt:"2026-09-02T00:00:00.000Z",packageRoot:"/secret"})).toThrow();off();expect(mocks.remove).toHaveBeenCalledWith(IPC_CHANNELS.MARKETPLACE_PACKAGE_CHANGED,registered);});
});
