import {mkdtemp,mkdir,writeFile,readFile,access} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";import {describe,expect,it} from "vitest";import {createSkillStorageLayout,stageSkillInstallation} from "./skill-installer";
async function source(root:string,body:string,disabled=false){const path=join(root,"security-review");await mkdir(path,{recursive:true});await writeFile(join(path,"SKILL.md"),`---\nname: security-review\ndescription: Review\n${disabled?"disable-model-invocation: true\n":""}---\n${body}`);return path;}
describe("skill installer",()=>{
 it("publishes versioned package and active projection",async()=>{const base=await mkdtemp(join(tmpdir(),"aw-install-")),layout=createSkillStorageLayout(base),src=await source(join(base,"input"),"workflow");const tx=await stageSkillInstallation({sourceDirectory:src,managedRoot:layout,version:"1.0.0"});const result=await tx.commit();expect(result.packagePath).toBe(join(layout.packagesRoot,"security-review","1.0.0"));expect(await readFile(join(layout.activeRoot,"security-review","SKILL.md"),"utf8")).toContain("workflow");await tx.finalize();});
 it("restores prior projection on rollback",async()=>{const base=await mkdtemp(join(tmpdir(),"aw-install-")),layout=createSkillStorageLayout(base);const first=await stageSkillInstallation({sourceDirectory:await source(join(base,"one"),"old"),managedRoot:layout,version:"1"});await first.commit();await first.finalize();const next=await stageSkillInstallation({sourceDirectory:await source(join(base,"two"),"new"),managedRoot:layout,version:"2"});await next.commit();await next.rollback();expect(await readFile(join(layout.activeRoot,"security-review","SKILL.md"),"utf8")).toContain("old");});
 it("adds OpenCode autoinvoke only to projection",async()=>{const base=await mkdtemp(join(tmpdir(),"aw-install-")),layout=createSkillStorageLayout(base),tx=await stageSkillInstallation({sourceDirectory:await source(join(base,"input"),"body",true),managedRoot:layout,version:"1"});await tx.commit();expect(await readFile(join(layout.activeRoot,"security-review","SKILL.md"),"utf8")).toContain("opencode/autoinvoke: false");expect(await readFile(join(layout.packagesRoot,"security-review","1","SKILL.md"),"utf8")).not.toContain("opencode/autoinvoke");});
 it("rollback is idempotent",async()=>{const base=await mkdtemp(join(tmpdir(),"aw-install-")),layout=createSkillStorageLayout(base),tx=await stageSkillInstallation({sourceDirectory:await source(join(base,"input"),"body"),managedRoot:layout});await tx.commit();await tx.rollback();await tx.rollback();await expect(access(join(layout.activeRoot,"security-review"))).rejects.toThrow();});
 it("rejects unsafe storage versions",async()=>{const base=await mkdtemp(join(tmpdir(),"aw-install-")),layout=createSkillStorageLayout(base),src=await source(join(base,"input"),"body");await expect(stageSkillInstallation({sourceDirectory:src,managedRoot:layout,version:"../escape"})).rejects.toThrow(/version/);});
 it("rejects EEXIST with different canonical content",async()=>{const base=await mkdtemp(join(tmpdir(),"aw-install-")),layout=createSkillStorageLayout(base);const first=await stageSkillInstallation({sourceDirectory:await source(join(base,"one"),"old"),managedRoot:layout,version:"1"});await first.commit();await first.finalize();const second=await stageSkillInstallation({sourceDirectory:await source(join(base,"two"),"different"),managedRoot:layout,version:"1"});await expect(second.commit()).rejects.toThrow(/collides/);expect(await readFile(join(layout.activeRoot,"security-review","SKILL.md"),"utf8")).toContain("old");});

});
