import BetterSqlite3 from "better-sqlite3";import {afterEach,beforeEach,describe,expect,it} from "vitest";import {bootstrapSchemaSql} from "../database/bootstrap";import {SkillRepository} from "./skill-repository";
let db:BetterSqlite3.Database,repo:SkillRepository;const installation={skillId:"security-review",version:"1",sourceKind:"local" as const,sourceRef:"local-import",contentDigest:`sha256:${"a".repeat(64)}`,name:"security-review",description:"Review",codexCompatibility:"supported" as const,opencodeCompatibility:"supported" as const,automaticInvocation:true,state:"pending_verification" as const};
beforeEach(()=>{db=new BetterSqlite3(":memory:");db.exec(bootstrapSchemaSql);db.pragma("foreign_keys=OFF");repo=new SkillRepository(db);});afterEach(()=>db.close());
describe("SkillRepository",()=>{
 it("persists installations",()=>{repo.saveInstallation(installation);expect(repo.setInstallationState("security-review","installed")).toMatchObject({state:"installed",automaticInvocation:true});});
 it("replaces an installation atomically",()=>{repo.saveInstallation(installation);repo.saveInstallation({...installation,version:"2"});expect(repo.listInstallations()).toHaveLength(1);expect(repo.getInstallation("security-review")?.version).toBe("2");});
 it("persists invocation lifecycle",()=>{repo.saveInstallation(installation);const item=repo.startInvocation({runId:"run",skillId:"security-review",version:"1",mode:"explicit"});repo.transitionInvocation(item.id,"loaded");expect(repo.listRunInvocations("run")[0]?.status).toBe("loaded");});
 it("rejects terminal transitions",()=>{const item=repo.startInvocation({runId:"run",skillId:"security-review",version:"1",mode:"explicit"});repo.transitionInvocation(item.id,"failed","code");expect(()=>repo.transitionInvocation(item.id,"loaded")).toThrow(/Invalid/);});
 it("removes installation but preserves history",()=>{repo.saveInstallation(installation);repo.startInvocation({runId:"run",skillId:"security-review",version:"1",mode:"explicit"});repo.removeInstallation("security-review");expect(repo.getInstallation("security-review")).toBeUndefined();expect(repo.listRunInvocations("run")).toHaveLength(1);});
});
