import {mkdtemp,writeFile,mkdir,symlink,link,chmod} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";import {describe,expect,it} from "vitest";import {MAX_SKILL_FILES,MAX_SKILL_FILE_BYTES,validateSkillPackage} from "./skill-validation";
async function fixture(name="security-review",body="Review boundaries",extra:Record<string,string|Buffer>={}){const base=await mkdtemp(join(tmpdir(),"aw-skill-")),root=join(base,name);await mkdir(root);await writeFile(join(root,"SKILL.md"),`---\nname: ${name}\ndescription: ${body}\n---\n# Workflow\n`);for(const [path,value] of Object.entries(extra)){await mkdir(join(root,path,".."),{recursive:true});await writeFile(join(root,path),value);}return root;}
describe("validateSkillPackage",()=>{
 it("validates text and creates stable digest",async()=>{const root=await fixture("security-review","Review",{"references/a.md":"# A"});const a=await validateSkillPackage(root),b=await validateSkillPackage(root);expect(a.files.map(x=>x.relativePath)).toEqual(["references/a.md","SKILL.md"].sort());expect(a.contentDigest).toBe(b.contentDigest);expect(a.descriptor.version).toMatch(/^0\.0\.0-local\./);});
 it("honors disable-model-invocation",async()=>{const root=await fixture();await writeFile(join(root,"SKILL.md"),"---\nname: security-review\ndescription: Review\ndisable-model-invocation: true\n---\n");expect((await validateSkillPackage(root)).descriptor.automaticInvocation).toBe(false);});
 it("rejects directory mismatch",async()=>{const root=await fixture();await writeFile(join(root,"SKILL.md"),"---\nname: other\ndescription: Review\n---\n");await expect(validateSkillPackage(root)).rejects.toThrow(/match/);});
 it("rejects missing description",async()=>{const root=await fixture();await writeFile(join(root,"SKILL.md"),"---\nname: security-review\n---\n");await expect(validateSkillPackage(root)).rejects.toThrow(/description/);});
 it("rejects scripts",async()=>await expect(validateSkillPackage(await fixture("security-review","Review",{"scripts/a.md":"x"}))).rejects.toThrow(/scripts/));
 it("rejects binary NUL bytes",async()=>await expect(validateSkillPackage(await fixture("security-review","Review",{"references/a.md":Buffer.from([0])}))).rejects.toThrow(/binary/));
 it("rejects symlinks",async()=>{const root=await fixture();await symlink(join(root,"SKILL.md"),join(root,"link.md"));await expect(validateSkillPackage(root)).rejects.toThrow(/symlink/);});
 it("rejects hard links",async()=>{const root=await fixture();await link(join(root,"SKILL.md"),join(root,"copy.md"));await expect(validateSkillPackage(root)).rejects.toThrow(/hard link/);});
 it("rejects executable files",async()=>{const root=await fixture("security-review","Review",{"a.md":"x"});await chmod(join(root,"a.md"),0o700);await expect(validateSkillPackage(root)).rejects.toThrow(/executable/);});
 it("rejects too many files",async()=>{const extra=Object.fromEntries(Array.from({length:MAX_SKILL_FILES},(_,i)=>[`r/${i}.md`,"x"]));await expect(validateSkillPackage(await fixture("security-review","Review",extra))).rejects.toThrow(/count/);});
 it("rejects oversized files",async()=>await expect(validateSkillPackage(await fixture("security-review","Review",{"a.md":"x".repeat(MAX_SKILL_FILE_BYTES+1)}))).rejects.toThrow(/size/));
 it("rejects YAML aliases",async()=>{const root=await fixture();await writeFile(join(root,"SKILL.md"),"---\nname: security-review\ndescription: &d Review\nmetadata: { copy: *d }\n---\n");await expect(validateSkillPackage(root)).rejects.toThrow(/aliases/);});
});
